In [1]:
import pandas as pd
import numpy as np
from titlecase import titlecase

In [2]:
books = pd.read_csv(r'C:\Users\Karen Fernandes\anaconda3\Files\BRS\datasets\Books.csv', dtype={3: str})
ratings = pd.read_csv(r'C:\Users\Karen Fernandes\anaconda3\Files\BRS\datasets\Ratings.csv')
users = pd.read_csv(r'C:\Users\Karen Fernandes\anaconda3\Files\BRS\datasets\Users.csv')

In [3]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271360 entries, 0 to 271359
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ISBN                 271360 non-null  object
 1   Book-Title           271360 non-null  object
 2   Book-Author          271358 non-null  object
 3   Year-Of-Publication  271360 non-null  object
 4   Publisher            271358 non-null  object
 5   Image-URL-S          271360 non-null  object
 6   Image-URL-M          271360 non-null  object
 7   Image-URL-L          271357 non-null  object
dtypes: object(8)
memory usage: 16.6+ MB

In [4]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1149780 entries, 0 to 1149779
Data columns (total 3 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   User-ID      1149780 non-null  int64
 1   ISBN         1149780 non-null  object
 2   Book-Rating  1149780 non-null  int64
dtypes: int64(2), object(1)
memory usage: 26.3+ MB

In [5]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278858 entries, 0 to 278857
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   User-ID   278858 non-null  int64
 1   Location  278858 non-null  object
 2   Age       168096 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 6.4+ MB

In [6]:
books.dtypes

ISBN                   object
Book-Title             object
Book-Author            object
Year-Of-Publication    object
Publisher              object
Image-URL-S            object
Image-URL-M            object
Image-URL-L            object
dtype: object

In [7]:
books.shape

(271360, 8)

In [8]:
ratings.shape

(1149780, 3)

In [9]:
users.shape

(278858, 3)

In [10]:
# convert the column names to snake case
books.columns = books.columns.str.lower().str.replace('-', '_')
ratings.columns = ratings.columns.str.lower().str.replace('-', '_')
users.columns = users.columns.str.lower().str.replace('-', '_')

In [11]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271360 entries, 0 to 271359
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   isbn                 271360 non-null  object
 1   book_title           271360 non-null  object
 2   book_author          271358 non-null  object
 3   year_of_publication  271360 non-null  object
 4   publisher            271358 non-null  object
 5   image_url_s          271360 non-null  object
 6   image_url_m          271360 non-null  object
 7   image_url_l          271357 non-null  object
dtypes: object(8)
memory usage: 16.6+ MB

In [12]:
# change uppercase to proper case for book_title and book_author column
books["book_title"] = books["book_title"].apply(lambda x: titlecase(str(x)) if isinstance(x, str) else x)
books["book_author"] = books["book_author"].apply(lambda x: titlecase(str(x)) if isinstance(x, str) else x)

In [13]:
books.head()

,isbn,book_title,book_author,year_of_publication,publisher,image_url_s,image_url_m,image_url_l
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo d'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

### Check for nulls

In [14]:
books.isnull().sum()

isbn                   0
book_title             0
book_author            2
year_of_publication    0
publisher              2
image_url_s            0
image_url_m            0
image_url_l            3
dtype: int64

In [15]:
users.isnull().sum()

user_id          0
location         0
age         110762
dtype: int64

In [16]:
ratings.isnull().sum()

user_id        0
isbn           0
book_rating    0
dtype: int64

### Check for duplicates

In [17]:
books.duplicated().sum()

np.int64(0)

In [18]:
ratings.duplicated().sum()

np.int64(0)

In [19]:
users.duplicated().sum()

np.int64(0)

## Popularily Based Recommendation System

In [20]:
df = ratings.merge(books, on = 'isbn')
df.head()

,user_id,isbn,book_rating,book_title,book_author,year_of_publication,publisher,image_url_s,image_url_m,image_url_l
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...

In [21]:
df.shape

(1031136, 10)

In [22]:
no_rating_df = df.groupby('book_title').count()['book_rating'].reset_index()
no_rating_df.rename(columns = {'book_rating': 'no_of_rating'}, inplace = True)
no_rating_df

                                               book_title  no_of_rating
0                                   Always Have Popsicles             1
1                    Apple Magic (The Collector's Series)             1
2        Ask Lily (Young Women of Faith: Lily Series, ...             1
3        Beyond IBM: Leadership Marketing and Finance ...             1
4        Clifford Visita El Hospital (Clifford El Gran...             1
...                                                   ...           ...
238166                                      Ã?Â?lpiraten.             2
238167                     Ã?Â?rger Mit Produkt X. Roman.             4
238168                                Ã?Â?sterlich Leben.             1
238169                              Ã?Â?stlich Der Berge.             3
238170                                  Ã?Â?thique en Toc             2

[238171 rows x 2 columns]

In [23]:
avg_rating_df = df.groupby('book_title', as_index=False)['book_rating'].mean()
avg_rating_df.rename(columns = {'book_rating': 'avg_of_rating'}, inplace = True)
avg_rating_df['avg_of_rating'] = avg_rating_df['avg_of_rating'].round(2)

In [24]:
avg_rating_df

                                               book_title  avg_of_rating
0                                   Always Have Popsicles           0.00
1                    Apple Magic (The Collector's Series)           0.00
2        Ask Lily (Young Women of Faith: Lily Series, ...           8.00
3        Beyond IBM: Leadership Marketing and Finance ...           0.00
4        Clifford Visita El Hospital (Clifford El Gran...           0.00
...                                                   ...            ...
238166                                      Ã?Â?lpiraten.           0.00
238167                     Ã?Â?rger Mit Produkt X. Roman.           5.25
238168                                Ã?Â?sterlich Leben.           7.00
238169                              Ã?Â?stlich Der Berge.           2.67
238170                                  Ã?Â?thique en Toc           4.00

[238171 rows x 2 columns]

In [25]:
# clamp the rating at a maximum of 5.0
avg_rating_df['avg_of_rating'] = avg_rating_df['avg_of_rating'].clip(upper=5.0)
avg_rating_df

                                               book_title  avg_of_rating
0                                   Always Have Popsicles           0.00
1                    Apple Magic (The Collector's Series)           0.00
2        Ask Lily (Young Women of Faith: Lily Series, ...           5.00
3        Beyond IBM: Leadership Marketing and Finance ...           0.00
4        Clifford Visita El Hospital (Clifford El Gran...           0.00
...                                                   ...            ...
238166                                      Ã?Â?lpiraten.           0.00
238167                     Ã?Â?rger Mit Produkt X. Roman.           5.00
238168                                Ã?Â?sterlich Leben.           5.00
238169                              Ã?Â?stlich Der Berge.           2.67
238170                                  Ã?Â?thique en Toc           4.00

[238171 rows x 2 columns]

In [26]:
popular_df = no_rating_df.merge(avg_rating_df, on = 'book_title')
popular_df

,book_title,no_of_rating,avg_of_rating
0,Always Have Popsicles,1,0.00
1,Apple Magic (The Collector's Series),1,0.00
2,"Ask Lily (Young Women of Faith: Lily Series, ...",1,5.00
3,Beyond IBM: Leadership Marketing and Finance ...,1,0.00
4,Clifford Visita El Hospital (Clifford El Gran...,1,0.00
...,...,...,...
238166,Ã?Â?lpiraten.,2,0.00
238167,Ã?Â?rger Mit Produkt X. Roman.,4,5.00
238168,Ã?Â?sterlich Leben.,1,5.00
238169,Ã?Â?stlich Der Berge.,3,2.67
238170,Ã?Â?thique en Toc,2,4.00

In [27]:
popular_df = popular_df[popular_df['no_of_rating']>=250].sort_values('avg_of_rating', ascending = False).head(50)

In [28]:
popular_df

,book_title,no_of_rating,avg_of_rating
79288,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.00
79268,Harry Potter and the Chamber of Secrets (Book 2),556,5.00
79280,Harry Potter and the Order of the Phoenix (Boo...,347,5.00
79276,Harry Potter and the Goblet of Fire (Book 4),387,5.00
79295,Harry Potter and the Sorcerer's Stone (Book 1),278,5.00
189434,The Hobbit : The Enchanting Prelude to the Lor...,281,5.00
185050,The Fellowship of the Ring (The Lord of the Ri...,368,4.95
79299,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.90
209825,"The Two Towers (The Lord of the Rings, Part 2)",260,4.88
216695,To Kill a Mockingbird,510,4.70
181112,The Da Vinci Code,898,4.64
177985,The Catcher in the Rye,449,4.55
185573,The Five People You Meet in Heaven,430,4.55
194283,The Lovely Bones: A Novel,1295,4.47
762,1984,284,4.45
204781,The Secret Life of Bees,774,4.45
142000,Prodigal Summer: A Novel,253,4.45
126656,Neverwhere,265,4.45
7970,A Wrinkle in Time,350,4.42
166216,Stupid White Men ...And Other Sorry Excuses fo...,283,4.36
220127,"Tuesdays With Morrie: An Old Man, a Young Man,...",493,4.35
189410,The Hitchhiker's Guide to the Galaxy,268,4.33
202618,The Red Tent (Bestselling Backlist),723,4.33
127386,Nickel and Dimed: On (Not) Getting by in America,335,4.29
92201,Into the Wild,252,4.27
62892,Fahrenheit 451,409,4.26
134105,Outlander,283,4.17
230159,Where the Heart Is (Oprah's Book Club (Paperba...,585,4.11
73723,Girl With a Pearl Earring,651,4.10
153417,Seabiscuit: An American Legend,275,4.10
2293,"A Child Called \It\"": One Child's Courage to S...",265,4.09
106137,Life of Pi,664,4.09
174171,The Bean Trees,389,4.09
14092,Angela's Ashes,279,4.08
75386,Good in Bed,492,4.05
63972,Fast Food Nation: The Dark Side of the All-Ame...,321,4.04
12427,American Gods,307,4.01
159045,Skipping Christmas,322,4.01
187304,"The Golden Compass (His Dark Materials, Book 1)",336,4.00
103943,Left Behind: A Novel of the Earth's Last Days ...,318,4.00
179137,The Color Purple,314,3.96
157706,Silence of the Lambs,256,3.96
155485,Seven Up (A Stephanie Plum Novel),278,3.89
172373,The Alchemist: A Fable About Following Your Dream,266,3.88
8437,About a Boy,279,3.83
78910,Hard Eight : A Stephanie Plum Novel (A Stephan...,269,3.83
167628,Suzanne's Diary for Nicholas,457,3.82
109266,Lord of the Flies,259,3.82
5824,A Prayer for Owen Meany,413,3.80
210529,"The Vampire Lestat (Vampire Chronicles, Book II)",301,3.78

In [29]:
popular_df = popular_df.merge(books, on = 'book_title').drop_duplicates('book_title')[['book_title', 'book_author', 'image_url_l', 'no_of_rating', 'avg_of_rating']]

In [30]:
popular_df

,book_title,book_author,image_url_l,no_of_rating,avg_of_rating
0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...,428,5.00
3,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...,556,5.00
6,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,347,5.00
10,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...,387,5.00
12,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,http://images.amazon.com/images/P/0590353403.0...,278,5.00
16,The Hobbit : The Enchanting Prelude to the Lor...,J.R.R. Tolkien,http://images.amazon.com/images/P/0345339681.0...,281,5.00
17,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. Tolkien,http://images.amazon.com/images/P/0345339703.0...,368,4.95
26,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...,575,4.90
28,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. Tolkien,http://images.amazon.com/images/P/0345339711.0...,260,4.88
39,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/0446310786.0...,510,4.70
47,The Da Vinci Code,Dan Brown,http://images.amazon.com/images/P/0385504209.0...,898,4.64
53,The Catcher in the Rye,J.D. Salinger,http://images.amazon.com/images/P/0316769487.0...,449,4.55
60,The Five People You Meet in Heaven,Mitch Albom,http://images.amazon.com/images/P/0786868716.0...,430,4.55
62,The Lovely Bones: A Novel,Alice Sebold,http://images.amazon.com/images/P/0316666343.0...,1295,4.47
63,1984,George Orwell,http://images.amazon.com/images/P/0451524934.0...,284,4.45
72,The Secret Life of Bees,Sue Monk Kidd,http://images.amazon.com/images/P/0142001740.0...,774,4.45
78,Prodigal Summer: A Novel,Barbara Kingsolver,http://images.amazon.com/images/P/0060959037.0...,253,4.45
79,Neverwhere,Neil Gaiman,http://images.amazon.com/images/P/0380789019.0...,265,4.45
84,A Wrinkle in Time,Madeleine l'Engle,http://images.amazon.com/images/P/0440998050.0...,350,4.42
90,Stupid White Men ...And Other Sorry Excuses fo...,Michael Moore,http://images.amazon.com/images/P/0060392452.0...,283,4.36
91,"Tuesdays With Morrie: An Old Man, a Young Man,...",Mitch Albom,http://images.amazon.com/images/P/0385484518.0...,493,4.35
94,The Hitchhiker's Guide to the Galaxy,Douglas Adams,http://images.amazon.com/images/P/0671461494.0...,268,4.33
103,The Red Tent (Bestselling Backlist),Anita Diamant,http://images.amazon.com/images/P/0312195516.0...,723,4.33
104,Nickel and Dimed: On (Not) Getting by in America,Barbara Ehrenreich,http://images.amazon.com/images/P/0805063897.0...,335,4.29
106,Into the Wild,Jon Krakauer,http://images.amazon.com/images/P/0385486804.0...,252,4.27
109,Fahrenheit 451,Ray Bradbury,http://images.amazon.com/images/P/3257208626.0...,409,4.26
122,Outlander,Diana Gabaldon,http://images.amazon.com/images/P/0440222915.0...,283,4.17
128,Where the Heart Is (Oprah's Book Club (Paperba...,Billie Letts,http://images.amazon.com/images/P/0446672211.0...,585,4.11
129,Girl With a Pearl Earring,Tracy Chevalier,http://images.amazon.com/images/P/0452282152.0...,651,4.10
133,Seabiscuit: An American Legend,Laura Hillenbrand,http://images.amazon.com/images/P/0449005615.0...,275,4.10
135,"A Child Called \It\"": One Child's Courage to S...",Dave Pelzer,http://images.amazon.com/images/P/1558743669.0...,265,4.09
137,Life of Pi,Yann Martel,http://images.amazon.com/images/P/0151008116.0...,664,4.09
141,The Bean Trees,Barbara Kingsolver,http://images.amazon.com/images/P/0060915544.0...,389,4.09
144,Angela's Ashes,Frank McCourt,http://images.amazon.com/images/P/0684874350.0...,279,4.08
146,Good in Bed,Jennifer Weiner,http://images.amazon.com/images/P/0743418174.0...,492,4.05
149,Fast Food Nation: The Dark Side of the All-Ame...,Eric Schlosser,http://images.amazon.com/images/P/0060938455.0...,321,4.04
150,American Gods,Neil Gaiman,http://images.amazon.com/images/P/0380789035.0...,307,4.01
152,Skipping Christmas,John Grisham,http://images.amazon.com/images/P/0385505833.0...,322,4.01
158,"The Golden Compass (His Dark Materials, Book 1)",Philip Pullman,http://images.amazon.com/images/P/037582345X.0...,336,4.00
166,Left Behind: A Novel of the Earth's Last Days ...,Tim Lahaye,http://images.amazon.com/images/P/0842329129.0...,318,4.00
168,The Color Purple,Alice Walker,http://images.amazon.com/images/P/0671617028.0...,314,3.96
174,Silence of the Lambs,Thomas Harris,http://images.amazon.com/images/P/0312924585.0...,256,3.96
177,Seven Up (A Stephanie Plum Novel),Janet Evanovich,http://images.amazon.com/images/P/0312265840.0...,278,3.89
179,The Alchemist: A Fable About Following Your Dream,Paulo Coelho,http://images.amazon.com/images/P/0062502174.0...,266,3.88
181,About a Boy,Nick Hornby,http://images.amazon.com/images/P/1573227331.0...,279,3.83
190,Hard Eight : A Stephanie Plum Novel (A Stephan...,Janet Evanovich,http://images.amazon.com/images/P/0312983867.0...,269,3.83
195,Suzanne's Diary for Nicholas,James Patterson,http://images.amazon.com/images/P/0316969443.0...,457,3.82
199,Lord of the Flies,William Gerald Golding,http://images.amazon.com/images/P/0399501487.0...,259,3.82
205,A Prayer for Owen Meany,John Irving,http://images.amazon.com/images/P/0345361792.0...,413,3.80
207,"The Vampire Lestat (Vampire Chronicles, Book II)",Anne Rice,http://images.amazon.com/images/P/0345313860.0...,301,3.78

## Collaborative Filtering Based Recommender System
Returning rows where the users have rated more than 200 books and books with minimum of 50 ratings

In [31]:
x = df.groupby('user_id').count()['book_rating']>200
users_rated_books = x[x].index

In [32]:
filtered_rating = df[df['user_id'].isin(users_rated_books)]

In [33]:
y = filtered_rating.groupby('book_title').count()['book_rating']>=50
popular_books = y[y].index

In [34]:
final_df = filtered_rating[filtered_rating['book_title'].isin(popular_books)]

In [35]:
pt_df = final_df.pivot_table(index = 'book_title', columns = 'user_id', values = 'book_rating')

In [36]:
pt_df.fillna(0, inplace = True)

In [37]:
pt_df

user_id,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
book_title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong to Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry Into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [38]:
from sklearn.metrics.pairwise import cosine_similarity

In [39]:
similarity_score = cosine_similarity(pt_df)

In [40]:
similarity_score.shape

(718, 718)

In [41]:
def recommend(book_name):
    # fetch index
    index = np.where(pt_df.index == book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_score[index])), key = lambda x:x[1], reverse = True)[1:11]

    data = []
    for i in similar_items:
        temp_df = books[books['book_title'] == pt_df.index[i[0]]]
        item = []
        item.extend(list(temp_df.drop_duplicates('book_title')['book_title'].values))
        item.extend(list(temp_df.drop_duplicates('book_title')['book_author'].values))
        item.extend(list(temp_df.drop_duplicates('book_title')['image_url_l'].values))

        data.append(item)

    return data

In [42]:
recommend('Harry Potter and the Prisoner of Azkaban (Book 3)')

[['Harry Potter and the Goblet of Fire (Book 4)',
  'J. K. Rowling',
  'http://images.amazon.com/images/P/0439139597.01.LZZZZZZZ.jpg'],
 ['Harry Potter and the Chamber of Secrets (Book 2)',
  'J. K. Rowling',
  'http://images.amazon.com/images/P/0439064872.01.LZZZZZZZ.jpg'],
 ['Harry Potter and the Order of the Phoenix (Book 5)',
  'J. K. Rowling',
  'http://images.amazon.com/images/P/043935806X.01.LZZZZZZZ.jpg'],
 ["Harry Potter and the Sorcerer's Stone (Book 1)",
  'J. K. Rowling',
  'http://images.amazon.com/images/P/0590353403.01.LZZZZZZZ.jpg'],
 ["Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))",
  'J. K. Rowling',
  'http://images.amazon.com/images/P/059035342X.01.LZZZZZZZ.jpg'],
 ['The Fellowship of the Ring (The Lord of the Rings, Part 1)',
  'J.R.R. Tolkien',
  'http://images.amazon.com/images/P/0345339703.01.LZZZZZZZ.jpg'],
 ["Charlotte's Web (Trophy Newbery)",
  'E. B. White',
  'http://images.amazon.com/images/P/0064400557.01.LZZZZZZZ.jpg'],
 ['Anne of Avonlea (Anne of Green Gables Novels (Paperback))',
  'L.M. Montgomery',
  'http://images.amazon.com/images/P/0553213148.01.LZZZZZZZ.jpg'],
 ['The Return of the King (The Lord of the Rings, Part 3)',
  'J.R.R. Tolkien',
  'http://images.amazon.com/images/P/0345339738.01.LZZZZZZZ.jpg'],
 ['Interview With the Vampire',
  'Anne Rice',
  'http://images.amazon.com/images/P/0345337662.01.LZZZZZZZ.jpg']]

In [43]:
sorted(list(enumerate(similarity_score[0])), key = lambda x:x[1], reverse = True)[1:6]

[(47, np.float64(0.2702651417103732)),
 (556, np.float64(0.2639619371123497)),
 (82, np.float64(0.23669374347400993)),
 (645, np.float64(0.23299389358170394)),
 (562, np.float64(0.2262639743141286))]

In [44]:
import pickle
pickle.dump(popular_df, open('popular.pkl', 'wb'))
pickle.dump(pt_df, open('pt_df.pkl', 'wb'))
pickle.dump(books, open('books.pkl', 'wb'))
pickle.dump(similarity_score, open('similarity_score.pkl', 'wb'))